name: Build gibbons

on:
  push:
    branches: ["**"]
  workflow_dispatch: {}

jobs:
  gibbons:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      issues: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: sbt

      - name: Build and test
        env:
          SBT_JUNIT_OUTPUT: ./junit-tests
        run: sbt 'test;assembly'

      - uses: EnricoMi/publish-unit-test-result-action@v1
        if: always() #runs even if there is a test failure
        with:
          files: junit-tests/*.xml

      - uses: guardian/actions-riff-raff@v4
        with:
          configPath: riff-raff.yaml
          projectName: Content Platforms::gibbons
          buildNumberOffset: 272
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          contentDirectories: |
            gibbons-reminder:
              - target/scala-2.12/gibbons.jar
            gibbons-cleanup:
              - target/scala-2.12/gibbons.jar            
            gibbons-unverified-cleanup:
              - target/scala-2.12/gibbons.jar
